name: Stable Firmware Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install PlatformioIO
        run: pip install platformio

      - name: Build firmware
        working-directory: firmware
        run: pio run

      - name: Prepare artifacts
        run: |
          mkdir output
          cp firmware/.pio/build/esp32dev/firmware.bin output/firmware.bin

      - name: Create Stable Release
        uses: softprops/action-gh-release@v2
        with:
          tags_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          prerelease: false
          files: output/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
